version: '3'

services:
  postgresdb:
    build:
      context:
        ./docker/postgres
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-init.db/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb

  nginx:
    build:
      context:
        ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - web
      - postgresdb
    ports:
      - "80:80"
    volumes:
      - ./static:/static
      - ./docker/nginx/certs:/etc/ssl/certs

volumes:
  pgdata: