# Generated by Django 3.2.8 on 2021-10-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_url', models.URLField(max_length=2000)),
                ('short_url', models.CharField(max_length=5)),
                ('clicks', models.IntegerField(default=0)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
