# Generated by Django 3.2.8 on 2021-10-31 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_urls_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='short_url',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
