# Generated by Django 3.2.8 on 2021-11-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_urls_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
