# Generated by Django 3.2.8 on 2021-11-10 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_alter_urls_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='owner',
            field=models.ForeignKey(default=mainapp.models.get_default_user, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
