# Generated by Django 3.2.8 on 2021-11-09 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_urls_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='owner',
            field=models.CharField(default='AnonymousUser', max_length=200),
        ),
    ]
