# Generated by Django 3.2.8 on 2021-11-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_urls_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='time_last_click',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
