# Generated by Django 3.2.8 on 2021-11-14 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0006_urls_time_last_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='Кол-во переходов'),
        ),
        migrations.AlterField(
            model_name='urls',
            name='long_url',
            field=models.URLField(max_length=2000, verbose_name='Длинная ссылка'),
        ),
        migrations.AlterField(
            model_name='urls',
            name='owner',
            field=models.ForeignKey(default=mainapp.models.get_default_user, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='urls',
            name='short_url',
            field=models.CharField(blank=True, max_length=5, verbose_name='Короткая ссылка'),
        ),
        migrations.AlterField(
            model_name='urls',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='urls',
            name='time_last_click',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время послед. перехода'),
        ),
    ]
